# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 10:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160613_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='saving_throws',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='subcharacterclass',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='app.ParentCharacterClass'),
        ),
    ]
