# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160705_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('Strength', 'measures bodily power, athletic training, and the extent to which you can exert raw physical force.'), ('Constitution', 'measures health, stamina, and vital force.'), ('Dexterity', 'measures agility, reflexes, and balance.'), ('Intelligence', 'measures mental acuity, accuracy of recall, and the ability to reason.'), ('Wisdom', 'reflects how attuned you are to the world around you and represents perceptiveness and intuition.'), ('Charisma', 'measures your ability to interact effectively with others. It includes such factors as confidence and eloquence, and it can represent a charming or commanding personality.')], max_length=50),
        ),
    ]
