# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-16 06:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161116_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('skill_choices', models.IntegerField(default=0)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('hp_die', models.IntegerField(default=0)),
                ('saving_throws', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('parent_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.Class')),
            ],
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
    ]
