# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-16 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161116_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='has_subclasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='subclass_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
