# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161116_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='has_subclasses',
        ),
        migrations.RemoveField(
            model_name='class',
            name='parent_class',
        ),
        migrations.RemoveField(
            model_name='class',
            name='weapons',
        ),
        migrations.AddField(
            model_name='class',
            name='hp_lvl',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'count': 1, 'die': 4}),
        ),
        migrations.AddField(
            model_name='class',
            name='skill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='class',
            name='skill_choices',
        ),
        migrations.AddField(
            model_name='class',
            name='skill_choices',
            field=models.ManyToManyField(to='app.Skill'),
        ),
        migrations.AddField(
            model_name='subclass',
            name='parent_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.Class'),
        ),
    ]
