# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161119_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='item',
            field=models.ManyToManyField(related_name='item', to='app.Item'),
        ),
    ]
