# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_weapon_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_restriction', models.SmallIntegerField(default=1)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.Spell')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_spells', to='app.SubClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='item',
        ),
        migrations.AddField(
            model_name='subclass',
            name='spells',
            field=models.ManyToManyField(through='app.ClassSpell', to='app.Spell'),
        ),
    ]
