# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20161119_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='spells',
            field=models.ManyToManyField(to='app.Spell'),
        ),
    ]
