# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-23 14:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_class_spells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('player_name', models.CharField(max_length=50)),
                ('character_name', models.CharField(max_length=50)),
                ('armor_class', models.IntegerField(default=8)),
                ('is_npc', models.BooleanField()),
                ('passive_wisdom', models.IntegerField(default=8)),
                ('initiative', models.IntegerField(default=8)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, null=True, size=None)),
                ('current_hit_points', models.IntegerField(default=8)),
                ('max_hit_points', models.IntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('current_turn', models.IntegerField(default=1)),
                ('turn_order', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), default=list, null=True, size=None)),
                ('characters', models.ManyToManyField(to='app.Character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['level', 'name']},
        ),
    ]
