# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170123_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
