# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20170124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstate',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='app.Encounter'),
        ),
    ]
