# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20170124_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterstate',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='characterstate',
            name='next_state',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.CharacterState'),
            preserve_default=False,
        ),
    ]
