# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170128_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
