# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20170128_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('round', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=0)),
                ('value_type', models.CharField(choices=[('weapon', 'Weapon'), ('spell', 'Spell'), ('environment', 'Environment')], default='weapon', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='characterstate',
            options={'ordering': ['-initiative_roll']},
        ),
        migrations.AddField(
            model_name='action',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.CharacterState'),
        ),
        migrations.AddField(
            model_name='action',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.CharacterState'),
        ),
        migrations.AddField(
            model_name='action',
            name='spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Spell'),
        ),
    ]
