# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-23 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20170219_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='characterstate',
            name='next_state',
        ),
    ]
