# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-01 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_clue_clueoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='app.Chapter'),
            preserve_default=False,
        ),
    ]
