# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 22:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('skill_choices', models.IntegerField(default=0)),
                ('armor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('hp_die', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentClass',
            fields=[
                ('baseplayerclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BasePlayerClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.baseplayerclass',),
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('baseplayerclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BasePlayerClass')),
                ('parent_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ParentClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.baseplayerclass',),
        ),
        migrations.AddField(
            model_name='parentclass',
            name='subclasses',
            field=models.ManyToManyField(to='app.SubClass'),
        ),
    ]
