# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['ability']},
        ),
        migrations.RenameField(
            model_name='baserace',
            old_name='attributes',
            new_name='ability_scores',
        ),
    ]
