# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 03:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160605_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('skill_choices', models.IntegerField(default=0)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('hp_die', models.IntegerField(default=0)),
                ('saving_throws', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='hp_die',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='saving_throws',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='skill_choices',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='parentcharacterclass',
            name='weapons',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='hp_die',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='saving_throws',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='skill_choices',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='subcharacterclass',
            name='weapons',
        ),
        migrations.AddField(
            model_name='parentcharacterclass',
            name='characterclass_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='app.CharacterClass'),
        ),
        migrations.AddField(
            model_name='subcharacterclass',
            name='characterclass_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.CharacterClass'),
            preserve_default=False,
        ),
    ]
