# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_baseplayerclass_saving_throws'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=7)),
                ('has_darkvision', models.BooleanField(default=False)),
                ('armor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=7)),
                ('has_darkvision', models.BooleanField(default=False)),
                ('armor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='app.ParentRace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
