# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 03:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160613_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='armor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='weapons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
