# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160514_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=7)),
                ('has_darkvision', models.BooleanField(default=False)),
                ('armor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('weapons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('traits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RacialTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='has_darkvision',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='parentrace',
            name='weapons',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='has_darkvision',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='weapons',
        ),
        migrations.AddField(
            model_name='parentrace',
            name='baserace_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseRace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subrace',
            name='baserace_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseRace'),
            preserve_default=False,
        ),
    ]
