# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160514_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacialTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=500)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BaseRace')),
            ],
        ),
        migrations.DeleteModel(
            name='RacialTraits',
        ),
    ]
