# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160514_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='racialtrait',
            name='trait_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
