# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 16:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160704_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='saving_throws',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
