# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 17:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_racialtrait_trait_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='racialtrait',
            name='trait_value',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='racialtrait',
            name='trait_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, default=list, size=None),
        ),
    ]
