# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160514_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserace',
            name='speed',
            field=models.IntegerField(default=30),
        ),
    ]
