# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_baserace_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baserace',
            name='traits',
        ),
        migrations.AlterField(
            model_name='racialtrait',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racialtraits', to='app.BaseRace'),
        ),
    ]
