# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160514_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TraitProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Item')),
                ('armor_value', models.IntegerField(choices=[(0, '0AC'), (1, '1AC'), (2, '2AC'), (3, '3AC'), (4, '4AC'), (5, '5AC'), (6, '6AC'), (7, '7AC'), (8, '8AC'), (9, '9AC'), (10, '10AC'), (11, '11AC'), (12, '12AC'), (13, '13AC'), (14, '14AC'), (15, '15AC'), (16, '16AC'), (17, '17AC'), (18, '18AC'), (19, '19AC'), (20, '20AC'), (21, '21AC'), (22, '22AC'), (23, '23AC'), (24, '24AC'), (25, '25AC'), (26, '26AC'), (27, '27AC'), (28, '28AC'), (29, '29AC')], default=8)),
                ('armor_class', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('shield', 'Shield')], max_length=30)),
                ('stealth_disadvantage', models.BooleanField(default=False)),
                ('strength_requirement', models.IntegerField(null=True)),
                ('has_dex_modifier', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=1)),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Item')),
                ('is_martial', models.BooleanField(default=False)),
                ('is_versatile', models.BooleanField(default=False)),
                ('is_ranged', models.BooleanField(default=False)),
                ('is_two_handed', models.BooleanField(default=False)),
                ('has_finesse', models.BooleanField(default=False)),
                ('requires_ammo', models.BooleanField(default=False)),
                ('damage', models.IntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20'), (100, 'd100')], default=4)),
                ('dice_count', models.IntegerField(choices=[(1, '1 dice'), (2, '2 dice'), (3, '3 dice'), (4, '4 dice'), (5, '5 dice'), (6, '6 dice'), (7, '7 dice')], default=1)),
                ('short_range', models.IntegerField(choices=[(None, 'Not Ranged'), (15, '15 ft.'), (60, '60 ft.'), (120, '120 ft.'), (320, '320 ft.'), (400, '400 ft.'), (600, '600 ft.')], null=True)),
                ('long_range', models.IntegerField(choices=[(None, 'Not Ranged'), (5, '5 ft.'), (20, '20 ft.'), (30, '30 ft.'), (80, '80 ft.'), (100, '100 ft.'), (150, '150 ft.')], null=True)),
                ('versatile_dmg', models.IntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20'), (100, 'd100')], null=True)),
                ('versatile_dice', models.IntegerField(choices=[(1, '1 dice'), (2, '2 dice'), (3, '3 dice'), (4, '4 dice'), (5, '5 dice'), (6, '6 dice'), (7, '7 dice')], null=True)),
                ('damage_type', models.CharField(choices=[('bludgeoning', 'Bludgeoning'), ('piercing', 'Piercing'), ('slashing', 'Slashing')], max_length=30)),
                ('special', models.TextField(max_length=500, null=True)),
            ],
            bases=('app.item',),
        ),
        migrations.AddField(
            model_name='traitproperty',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Item'),
        ),
        migrations.AddField(
            model_name='traitproperty',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='app.Trait'),
        ),
        migrations.AddField(
            model_name='trait',
            name='item_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.TraitProperty'),
        ),
        migrations.AddField(
            model_name='item',
            name='traits',
            field=models.ManyToManyField(through='app.TraitProperty', to='app.Trait'),
        ),
    ]
