# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160520_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='item_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.TraitProperty'),
        ),
    ]
