# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160520_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='has_finesse',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_two_handed',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='long_range',
            field=models.IntegerField(blank=True, choices=[(None, 'Not Ranged'), (5, '5 ft.'), (20, '20 ft.'), (30, '30 ft.'), (80, '80 ft.'), (100, '100 ft.'), (150, '150 ft.')], null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='short_range',
            field=models.IntegerField(blank=True, choices=[(None, 'Not Ranged'), (15, '15 ft.'), (60, '60 ft.'), (120, '120 ft.'), (320, '320 ft.'), (400, '400 ft.'), (600, '600 ft.')], null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='special',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='versatile_dice',
            field=models.IntegerField(blank=True, choices=[(1, '1 dice'), (2, '2 dice'), (3, '3 dice'), (4, '4 dice'), (5, '5 dice'), (6, '6 dice'), (7, '7 dice')], null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='versatile_dmg',
            field=models.IntegerField(blank=True, choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20'), (100, 'd100')], null=True),
        ),
    ]
