# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160520_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='is_martial',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_ranged',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='is_versatile',
        ),
    ]
