# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 17:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_weapon_requires_ammo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('level', models.SmallIntegerField(default=0)),
                ('requires_concentration', models.BooleanField(default=False)),
                ('casting_time', models.CharField(max_length=255)),
                ('components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('spell_range', models.CharField(max_length=255)),
                ('spell_shape', models.CharField(choices=[(None, 'None'), ('cone', 'Cone'), ('straight', 'Straight Line'), ('wall', 'Wall'), ('pb', 'Point Blank Area'), ('square area', 'Area')], max_length=30, null=True)),
                ('duration', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
