# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import fifth_ed_spells.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='is_origin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='is_ritual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=fifth_ed_spells.app.models.default_components, size=None),
        ),
    ]
