# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_auto_20160527_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('character_name', models.CharField(max_length=300)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='is_origin',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='is_ritual',
        ),
        migrations.AddField(
            model_name='spell',
            name='components_desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(default='???', max_length=50),
        ),
        migrations.AddField(
            model_name='spellproperty',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Spell'),
        ),
    ]
